FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

# Define the user as a build argument
ARG user=fedora

# Install dependencies using microdnf (standard for fedora-minimal)
RUN microdnf install -y java-17-openjdk-headless openssl shadow-utils \
    && microdnf clean all

# Create the user and set up environment
RUN useradd $user -g root
ENV container=oci \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Set working directory
WORKDIR /home/fedora

# Download the MockServer JAR
RUN curl "https://repo.maven.apache.org/maven2/org/mock-server/mockserver-netty/7.0.0/mockserver-netty-7.0.0-jar-with-dependencies.jar" -L -o /home/fedora/mockserver.jar && \
    chown fedora:root /home/fedora/mockserver.jar

RUN curl -L "https://repo.maven.apache.org/maven2/org/graalvm/polyglot/polyglot/25.0.3/polyglot-25.0.3.jar" -o /home/fedora/polyglot.jar \
    && curl -L "https://repo.maven.apache.org/maven2/org/graalvm/sdk/collections/25.0.3/collections-25.0.3.jar" -o /home/fedora/collections.jar \
    && curl -L "https://repo.maven.apache.org/maven2/org/graalvm/sdk/nativeimage/25.0.3/nativeimage-25.0.3.jar" -o /home/fedora/nativeimage.jar \
    && curl -L "https://repo.maven.apache.org/maven2/org/graalvm/sdk/word/25.0.3/word-25.0.3.jar" -o /home/fedora/word.jar \
    && curl -L "https://repo.maven.apache.org/maven2/org/graalvm/sdk/jniutils/25.0.3/jniutils-25.0.3.jar" -o /home/fedora/jniutils.jar \
    && curl -L "https://repo.maven.apache.org/maven2/org/graalvm/js/js-language/25.0.3/js-language-25.0.3.jar" -o /home/fedora/js-language.jar \
    && curl -L "https://repo.maven.apache.org/maven2/org/graalvm/truffle/truffle-runtime/25.0.3/truffle-runtime-25.0.3.jar" -o /home/fedora/truffle-runtime.jar \
    && curl -L "https://repo.maven.apache.org/maven2/org/graalvm/truffle/truffle-api/25.0.3/truffle-api-25.0.3.jar" -o /home/fedora/truffle-api.jar \
    && curl -L "https://repo.maven.apache.org/maven2/org/graalvm/regex/regex/25.0.3/regex-25.0.3.jar" -o /home/fedora/regex.jar \
    && curl -L "https://repo.maven.apache.org/maven2/org/graalvm/shadowed/icu4j/25.0.3/icu4j-25.0.3.jar" -o /home/fedora/icu4j.jar \
    && chown fedora:root /home/fedora/*.jar

# Copy local entrypoint script and other files
COPY --chown=fedora:root entrypoint .

# Set permissions as per original image history
RUN chmod ug+rwx . && chmod ug+r mockserver.jar && chmod ug+rx entrypoint

# Final configuration
USER fedora
EXPOSE 1080/tcp
CMD ["./entrypoint"]
