FROM registry.access.redhat.com/ubi10/ubi-micro:latest

ARG AUTHORINO_VERSION=0.23.0

ARG TARGETARCH

COPY tmp/authorino/authorino-${AUTHORINO_VERSION}/authorino-${TARGETARCH} /usr/local/bin/authorino

USER 65532:65532

EXPOSE 50051
ENTRYPOINT ["/usr/local/bin/authorino"]
