apiVersion: v1
kind: Pod
metadata:
  name: echopulse-pod
  labels:
    app: echopulse
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
  containers:
  - name: echopulse-container
    image: image-registry.openshift-image-registry.svc:5000/echopulse/echopulse:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
      name: http
    env:
    - name: TARGET_URL
      value: "http://echopulse-default-svc:8080/echo"
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 15